name: cnv-psychosis
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn==1.5.2
  - statsmodels
  - matplotlib
  - seaborn
  - imbalanced-learn==0.12.3
  - scikit-posthocs
  - snakemake-minimal
  - bedtools
  - pybedtools
  - pyyaml
  - tqdm
  - json5
  - nbconvert
  - nbclient
  - ipykernel
  - jupyter
  - pip
  - pip:
      - statannotations
