name: cnv-psychosis
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - imbalanced-learn
  - scikit-posthocs
  - snakemake-minimal
  - bedtools
  - pybedtools
  - pyyaml
  - tqdm
  - json5
  - pip
  - pip:
      - statannotations
